image: gitpod/workspace-python-3.11

tasks:
  - name: Setup Python Environment
    init: |
      python -m venv venv
      source venv/bin/activate
      pip install -r requirements.txt
    command: |
      source venv/bin/activate
      python run.py

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python