name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          FLASK_APP: couchbase-flask-starter
          COUCHBASE_CONNECTION_STRING: ${{ secrets.COUCHBASE_CONNECTION_STRING }}
          COUCHBASE_USERNAME: ${{ secrets.COUCHBASE_USERNAME }}
          COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
          COUCHBASE_USE_CAPELLA: ${{ vars.COUCHBASE_USE_CAPELLA || 'false' }}
          COUCHBASE_DEFAULT_BUCKET: ${{ secrets.COUCHBASE_DEFAULT_BUCKET || 'default' }}
          COUCHBASE_DEFAULT_SCOPE: ${{ secrets.COUCHBASE_DEFAULT_SCOPE || '_default' }}
          COUCHBASE_DEFAULT_COLLECTION: ${{ secrets.COUCHBASE_DEFAULT_COLLECTION || '_default' }}
        run: |
          print("Bucket name", os.environ['COUCHBASE_DEFAULT_BUCKET'])
          pytest tests/test_app.py
