name: Test Couchbase connection

on: [workflow_dispatch]
defaults:
  run:
    shell: bash

env:
  COUCHBASE_DEFAULT_BUCKET: flask_${{ vars.COUCHBASE_DEFAULT_BUCKET }}
  COUCHBASE_DEFAULT_SCOPE: ${{ github.head_ref || github.ref_name }}_${{ vars.COUCHBASE_DEFAULT_SCOPE }}
  COUCHBASE_DEFAULT_COLLECTION: ${{ vars.COUCHBASE_DEFAULT_COLLECTION || '_default' }}
  COUCHBASE_CONNECTION_STRING: ${{ secrets.COUCHBASE_CONNECTION_STRING }}
  COUCHBASE_USERNAME: ${{ secrets.COUCHBASE_USERNAME }}
  COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
  COUCHBASE_USE_CAPELLA: ${{ vars.COUCHBASE_USE_CAPELLA || false }}
  COUCHBASE_OTLP_ENABLED: ${{ vars.COUCHBASE_OTLP_ENABLED || false }}

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: ldoguin/setup-cbsh@develop
      with:
        version: 'nightly'
        branch: 'main'
        enable-plugins: ''
        config: ${{ secrets.CBSHELL_CONFIG }}
    - name: Setup Couchbase Bucket, Scope, Collection
      run: |
        source ${{ github.workspace }}/scripts/dbSetup.nu
        dbSetup $COUCHBASE_DEFAULT_BUCKET $COUCHBASE_DEFAULT_SCOPE $COUCHBASE_DEFAULT_COLLECTION
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run connection test
      env:
        FLASK_APP: couchbase-flask-starter
        COUCHBASE_CONNECTION_STRING: ${{ secrets.COUCHBASE_CONNECTION_STRING }}
        COUCHBASE_USERNAME: ${{ secrets.COUCHBASE_USERNAME }}
        COUCHBASE_PASSWORD: ${{ secrets.COUCHBASE_PASSWORD }}
      run: |
        python -c "from app import create_app; app = create_app(); print('Connection successful')"
    - name: Tear Down Bucket
      run: |
        cb-env bucket $COUCHBASE_DEFAULT_BUCKET
        scopes drop $COUCHBASE_DEFAULT_SCOPE